---
version: "3.8"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: ${ELASTICSEARCH_CONTAINER_NAME}
    ports:
      - "${ES_PORT}:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=${SECURITY_ENABLED}
    mem_limit: ${ELASTIC_MEMORY_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -X GET http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    depends_on:
      - elastic
    container_name: ${KIBANA_CONTAINER_NAME}
    ports: 
    -  "${KIBANA_PORT}:5601"
    links: 
      - elastic
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic:${ES_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: ${KIBANA_MEMORY_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  elk: {}
